# Generated by Django 3.2.7 on 2022-02-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='cookie_json',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='scraper',
            name='nonce',
            field=models.CharField(default='default', max_length=120),
        ),
        migrations.AddField(
            model_name='scraper',
            name='user_id',
            field=models.BigIntegerField(default=1),
        ),
    ]
