# Generated by Django 3.2.7 on 2022-02-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20220204_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='cookie_json',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='nonce',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
