# Generated by Django 3.2.7 on 2022-02-04 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20220204_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
