# Generated by Django 3.2.7 on 2022-02-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_scraper_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='nonce',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
