# Generated by Django 3.2.7 on 2021-12-07 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_bankcredit'),
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pod_ref_num', models.CharField(max_length=80)),
                ('transaction_id', models.CharField(max_length=150)),
                ('transaction_date', models.CharField(max_length=50)),
                ('amount', models.BigIntegerField()),
                ('receiver_full_name', models.CharField(max_length=80)),
                ('destination_iban', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=80)),
                ('end_to_end_id', models.CharField(max_length=120)),
                ('transaction_code', models.CharField(max_length=50)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.shop')),
            ],
        ),
    ]
