# Generated by Django 3.2.7 on 2021-12-27 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='end_to_end_id',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='paid_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
