# Generated by Django 3.2.7 on 2021-12-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_withdraw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdraw',
            name='description',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='destination_iban',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='destination_sheba',
            field=models.CharField(default='IR-test', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='end_to_end_id',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='pod_ref_num',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='transaction_code',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='transaction_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='transaction_id',
            field=models.CharField(max_length=60),
        ),
    ]
