# Generated by Django 3.2.7 on 2022-01-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20211227_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='amount_without_commission',
            field=models.BigIntegerField(default=models.BigIntegerField()),
        ),
    ]
