# Generated by Django 3.2.7 on 2022-01-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20211227_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdraw',
            old_name='amount',
            new_name='amount_without_commission',
        ),
        migrations.AddField(
            model_name='withdraw',
            name='paid_amount',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
