# Generated by Django 3.2.7 on 2022-01-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_withdraw_amount_without_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='amount_without_commission',
            field=models.BigIntegerField(),
        ),
    ]
