# Generated by Django 3.2.7 on 2022-01-03 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_withdraw_amount_without_commission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='withdraw',
            old_name='amount',
            new_name='paid_amount',
        ),
    ]
