# Generated by Django 3.2.7 on 2021-12-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taglocation',
            name='x',
            field=models.SmallIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='taglocation',
            name='y',
            field=models.SmallIntegerField(default=50),
        ),
    ]
