# Generated by Django 3.2.7 on 2021-10-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='display_image',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
