# Generated by Django 3.2.7 on 2022-01-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_last_scrape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='last_scrape',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
