# Generated by Django 3.2.7 on 2021-11-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='instagram_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
