# Generated by Django 3.2.7 on 2021-11-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_instagram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
    ]
