# Generated by Django 3.2.7 on 2021-11-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='original_price',
        ),
    ]
