# Generated by Django 3.2.7 on 2022-01-15 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_discount_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcredit',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_credit_cards', to='shop.shop'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_discount', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='post',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_posts', to='shop.shop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_image_products', to='shop.productimage'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_product_images', to='shop.post'),
        ),
        migrations.AlterField(
            model_name='taglocation',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_tag', to='shop.product'),
        ),
    ]
