# Generated by Django 3.2.7 on 2022-01-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20220103_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='commission_percent',
            field=models.SmallIntegerField(default=5),
        ),
    ]
