# Generated by Django 3.2.7 on 2021-12-07 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_bankcredit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcredit',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.shop'),
        ),
    ]
