# Generated by Django 3.2.7 on 2022-01-17 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0005_auto_20220115_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='wallet',
        ),
        migrations.AddField(
            model_name='shop',
            name='bio',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='shop',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_vendor', to=settings.AUTH_USER_MODEL),
        ),
    ]
