# Generated by Django 3.2.7 on 2022-01-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20220117_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='delivery',
            field=models.IntegerField(choices=[(0, 'Not Free'), (1, 'In City'), (2, 'In Country')], default=0),
        ),
    ]
