# Generated by Django 3.2.7 on 2022-01-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_shop_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='preparation',
            field=models.IntegerField(choices=[(0, 'Two Hours'), (1, 'Twelve Hours'), (2, 'One Day'), (3, 'Three Days'), (4, 'One Week')], default=2),
        ),
    ]
