# Generated by Django 3.2.7 on 2022-01-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_shop_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='preparation',
            field=models.IntegerField(choices=[(0, 'Two Hours'), (1, 'Twelve Hours'), (2, 'One Day'), (3, 'Three Days'), (4, 'One Week')]),
        ),
    ]
