# Generated by Django 3.2.7 on 2022-01-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_shopdiscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shortcode',
            field=models.CharField(max_length=25),
        ),
    ]
