# Generated by Django 3.2.7 on 2022-01-25 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_post_shortcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopdiscount',
            old_name='end_at',
            new_name='finish_at',
        ),
    ]
