# Generated by Django 3.2.7 on 2022-01-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rename_end_at_shopdiscount_finish_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='last_scrape',
            field=models.DateTimeField(),
        ),
    ]
