# Generated by Django 3.2.7 on 2022-02-11 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_shop_last_scrape'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_everywhere', models.BooleanField()),
                ('city_free_cost', models.IntegerField(choices=[(0, 'Not Free'), (1, 'Occasionally Free'), (2, 'Totally Free')])),
                ('country_free_cost', models.IntegerField(choices=[(0, 'Not Free'), (1, 'Occasionally Free'), (2, 'Totally Free')])),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_shipment', to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='OccasionallyFreeDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'City'), (1, 'Country')])),
                ('free_from', models.PositiveIntegerField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occasionally_free_shipment', to='shop.shipment')),
            ],
            options={
                'unique_together': {('shipment', 'type')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'National Post'), (1, 'Online Delivery')])),
                ('base', models.PositiveIntegerField()),
                ('per_kilo', models.PositiveIntegerField()),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_price_shipment', to='shop.shipment')),
            ],
            options={
                'unique_together': {('shipment', 'type')},
            },
        ),
    ]
