# Generated by Django 3.2.7 on 2022-02-12 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_deliveryprice_occasionallyfreedelivery_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='delivery',
        ),
    ]
