# Generated by Django 3.2.7 on 2022-02-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_shop_delivery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='city_free_cost',
            new_name='city_cost',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='country_free_cost',
            new_name='country_cost',
        ),
    ]
