# Generated by Django 3.2.7 on 2022-02-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20220212_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='country_cost',
            field=models.IntegerField(choices=[(0, 'Not Free'), (1, 'Occasionally Free'), (2, 'Totally Free')], null=True),
        ),
    ]
