# Generated by Django 3.2.7 on 2022-02-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_shipment_country_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='has_national_post',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='has_online_delivery',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
