# Generated by Django 3.2.7 on 2022-02-13 15:52

from django.db import migrations


def create_existing_shops_shipment(apps, schema_editor):
    ShipmentModel = apps.get_model('shop', 'Shipment')
    DeliveryPriceModel = apps.get_model('shop', 'DeliveryPrice')
    ShopModel = apps.get_model('shop', 'Shop')
    shops = ShopModel.objects.all()

    for shop in shops:
        shipment_data = {
            "shop": shop,
            "send_everywhere": True,
            "has_national_post": True,
            "has_online_delivery": False,
            "city_cost": 0,
            "country_cost": 0,
        }

        shipment = ShipmentModel.objects.create(**shipment_data)

        national_post = {
            "shipment": shipment,
            "type": 0,
            "base": 13000,
            "per_kilo": 2700
        }
        DeliveryPriceModel.objects.create(**national_post)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20220213_1619'),
    ]

    operations = [
        migrations.RunPython(create_existing_shops_shipment)
    ]
