# Generated by Django 3.2.7 on 2022-03-28 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_auto_20220328_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopcreationstep',
            name='phone',
        ),
    ]
