# Generated by Django 3.2.7 on 2022-03-28 12:13

from django.db import migrations


def create_shop_creation_step_models(apps, schema_editor):
    ShopCreationStepModel = apps.get_model('shop', 'ShopCreationStep')

    ShopModel = apps.get_model('shop', 'Shop')
    shops = ShopModel.objects.all()

    for shop in shops:
        data = {
            'vendor': shop.vendor,
            'email': shop.email,
            'instagram_username': shop.instagram_username,
            'step': 'CREATED',
        }
        ShopCreationStepModel.objects.create(**data)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_shopcreationstep_phone'),
    ]

    operations = [
        migrations.RunPython(create_shop_creation_step_models)
    ]
