# Generated by Django 3.2.7 on 2022-03-30 15:29

from django.db import migrations, models


def initCatories(apps, schema_editor):
    categories = ('آرایشی و بهداشتی', 'پوشاک', 'صنایع دستی', 'دکوری و تزیینی', 'لوازم خانگی', 'گل و گیاه', 'مواد غذایی',
                  'عطاری', 'ورزش و سفر')
    CategoryModel = apps.get_model('shop', 'Category')
    for c in categories:
        category_obj = CategoryModel(name=c)
        category_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_shopcreationstep_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RunPython(initCatories),
    ]
