# Generated by Django 3.2.7 on 2021-11-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='critical',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
