# Generated by Django 3.2.7 on 2021-11-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_issue_critical'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_customer_project',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
