# Generated by Django 3.2.7 on 2021-11-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_issue_is_customer_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='user',
        ),
    ]
