# Generated by Django 3.2.7 on 2021-11-25 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopOrder',
            new_name='Order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='shop_order',
            new_name='order',
        ),
    ]
