# Generated by Django 3.2.7 on 2021-12-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Canceled'), (1, 'Awaiting Payment'), (2, 'Paid'), (3, 'Verified'), (4, 'Shipped'), (5, 'Received')]),
        ),
    ]
