# Generated by Django 3.2.7 on 2021-12-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='canceled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_by',
            field=models.IntegerField(choices=[(0, 'Personal Delivery'), (1, 'Online Delivery'), (2, 'Offline Delivery'), (3, 'Post')], null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='verified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Awaiting Payment'), (1, 'Paid'), (2, 'Verified'), (3, 'Shipped'), (4, 'Received'), (5, 'Canceled')]),
        ),
    ]
