# Generated by Django 3.2.7 on 2022-01-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_ordershopdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_discount_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_final_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_original_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_title',
            field=models.CharField(default='default title', max_length=40),
        ),
    ]
