# Generated by Django 3.2.7 on 2022-01-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211230_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipped_by',
            field=models.IntegerField(choices=[(0, 'Personal Delivery'), (1, 'Online Delivery'), (2, 'Offline Delivery'), (3, 'National Post')], null=True),
        ),
    ]
