# Generated by Django 3.2.7 on 2021-11-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20211128_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentinvoice',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='PaymentDetail',
        ),
        migrations.DeleteModel(
            name='PaymentInvoice',
        ),
    ]
