# Generated by Django 3.2.7 on 2022-01-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20220124_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product_discount_percent',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_final_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_original_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_title',
            field=models.CharField(max_length=40),
        ),
    ]
