# Generated by Django 3.2.7 on 2021-12-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20211130_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Awaiting Payment'), (2, 'Paid'), (3, 'Verified'), (4, 'Shipped'), (5, 'Received'), (6, 'Canceled')]),
        ),
    ]
