# Generated by Django 3.2.7 on 2022-02-15 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_remove_orderitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDeliveryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.IntegerField()),
                ('type', models.IntegerField()),
                ('base', models.PositiveIntegerField()),
                ('per_kilo', models.PositiveIntegerField()),
                ('destination_province', models.CharField(max_length=30)),
                ('destination_city', models.CharField(max_length=30)),
                ('destination_address', models.TextField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
