# Generated by Django 3.2.7 on 2022-02-21 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderdeliveryprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipped_by',
        ),
    ]
